
spring:
  jpa:
    show-sql: true 
    generate-ddl: false
    hibernate: 
      ddl-auto: none  

multitenancy: 
  mtapp: 
    dataSources: 
      -
        tenantId: tenant_1 
        url: jdbc:mysql://localhost:3306/multi_tenancy_en_schema?useSSL=false
        username: root
        password: mysql
        driverClassName: com.mysql.jdbc.Driver 
      -
        tenantId: tenant_2
        url: jdbc:mysql://localhost:3306/multi_tenancy_fr_schema?useSSL=false
        username: root
        password: mysql
        driverClassName: com.mysql.jdbc.Driver
